CREATE TABLE Member (
	M_ID	VARCHAR2(30)	NOT NULL,
	M_PW	VARCHAR2(30)	NOT NULL,
	M_AUTH	VARCHAR2(30)	NOT NULL,
	M_NAME	VARCHAR2(30)	NOT NULL,
	M_NICK	DATE	NOT NULL,
	M_BIRTH	VARCHAR2(30)	NOT NULL,
	M_GENDER	CHAR	NOT NULL,
	M_PHONE	VARCHAR2(100)	NOT NULL,
	M_EMAIL	VARCHAR2(60)	NOT NULL,
	M_ADDRESS	VARCHAR2(500)	NOT NULL,
	M_ADDRESSDETAIL	VARCHAR2(500)	NOT NULL,
	M_CREATEDATE	DATE	NOT NULL,
	M_DELETEDATE	DATE	NOT NULL
);

CREATE TABLE Profile (
	R_N	NUMBER	NOT NULL,
	B_N	VARCHAR2	NOT NULL,
	M_ID2	VARCHAR2(30)	NOT NULL
);

CREATE TABLE Board_Recruit (
	B_N	VARCHAR2	NOT NULL,
	M_ID	VARCHAR2(30)	NOT NULL,
	CA_N	NUMBER	NOT NULL,
	B_TYPE	CHAR	NOT NULL	DEFAULT 모집중	COMMENT '모집중, 모집마감',
	B_TILTE	VARCHAR2(500)	NOT NULL,
	B_CONTENT	VARCHAR2(2000)	NOT NULL,
	B_TOTAL	NUMBER	NOT NULL,
	B_ATTEND	NUMBER	NULL,
	B_PLACE	VARCHAR2	NOT NULL,
	B_FEE	NUMBER	NULL,
	B_MATCH	CHAR	NULL,
	B_GENDER	CHAR	NULL,
	B_MINAGE	NUMBER	NULL,
	B_MAXAGE	NUMBER	NULL,
	B_EQUIP	CHAR	NULL,
	B_MINPEOPLE	NUMBER	NULL,
	B_PROGRESS	VARCHAR2(2000)	NULL,
	B_SHOWER	CHAR	NULL,
	B_PARKING	CHAR	NULL,
	B_RENTAL	CHAR	NULL,
	B_CLOTH	CHAR	NULL,
	B_FACILITY	VARCHAR2(2000)	NULL,
	B_TIMESTAMP	DATE	NULL,
	B_VIEW	NUMBER	NULL,
	TART_DATE	DATE	NULL,
	END_DATE	DATE	NULL
);

CREATE TABLE Comment (
	C_N	NUMBER	NOT NULL,
	BM_N	NUMBER	NOT NULL,
	M_ID	VARCHAR2(30)	NOT NULL,
	Image_N	NUMBER	NOT NULL,
	C_COMMENT	VARCHAR2(2000)	NOT NULL,
	C_TIMESTAMP	DATE	NOT NULL
);

CREATE TABLE Chating (
	B_N	VARCHAR2	NOT NULL,
	M_ID	VARCHAR2(30)	NOT NULL,
	SEDN_ID	VARCHAR(255)	NULL,
	SENDTIME	VARCHAR(255)	NULL,
	MESSAGE	VARCHAR(255)	NULL,
	Field	VARCHAR(255)	NULL
);

CREATE TABLE TIME (
	B_N	VARCHAR2	NOT NULL,
	DAYWEEK	DATE	NULL,
	TIME	DATE	NULL
);

CREATE TABLE Application (
	AP_N	NUMBER	NOT NULL,
	B_N	VARCHAR2	NOT NULL,
	M_ID	VARCHAR2(30)	NOT NULL,
	AP_TIMESTAMP	DATE	NULL
);

CREATE TABLE Review (
	R_N	NUMBER	NOT NULL,
	B_N	VARCHAR2	NOT NULL,
	M_ID	VARCHAR2(30)	NOT NULL,
	GRADE	CHAR	NULL,
	R_CONTENT	VARCHAR2(2000)	NULL,
	R_TIMESTAMP	DATE	NULL
);

CREATE TABLE Category (
	CA_N	NUMBER	NOT NULL,
	CA_EXERCISE	CHAR	NULL
);

CREATE TABLE Board_Market (
	BM_N	NUMBER	NOT NULL,
	M_ID	VARCHAR2(30)	NOT NULL,
	CA_N	NUMBER	NOT NULL,
	Image_N	NUMBER	NOT NULL,
	B/M_TITLE	VARCHAR2(500)	NULL,
	BM_CONTENT	VARCHAR2(2000)	NULL,
	BM_TIMESTAMP	DATE	NULL,
	BM_VIEW	NUMBER	NULL
);

CREATE TABLE Image (
	Image_N	NUMBER	NOT NULL,
	Image_Src	VARCHAR2(80)	NULL
);

CREATE TABLE Board_Notice (
	BN_N	NUMBER	NOT NULL,
	M_ID	VARCHAR2(30)	NOT NULL,
	BN_TITLE	VARCHAR2(500)	NOT NULL,
	BN_CONTENT	VARCHAR2(20000)	NOT NULL,
	BN_TIMESTAMP	DATE	NOT NULL
);

CREATE TABLE Wish (
	W_N	NUMBER	NOT NULL,
	B_N	VARCHAR2	NOT NULL,
	M_ID	VARCHAR2(30)	NOT NULL,
	CA_N	NUMBER	NOT NULL
);

CREATE TABLE Board_Question (
	BQ_N	NUMBER	NOT NULL,
	M_ID	VARCHAR2(30)	NOT NULL,
	BQ_TITLE	VARCHAR2(50)	NOT NULL,
	BQ_CONTENT	VARCHAR2(2000)	NOT NULL,
	BQ_TIMESTAMP	DATE	NOT NULL
);

CREATE TABLE Report (
	R_N	NUMBER	NOT NULL,
	M_ID	VARCHAR2(30)	NOT NULL,
	R_TYPE	CHAR	NOT NULL,
	R_TITLE	VARCHAR2(50)	NOT NULL,
	R_CONTENT	VARCHAR2(2000)	NOT NULL,
	R_TIMESTAMP	DATE	NOT NULL
);

ALTER TABLE Member ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	M_ID
);

ALTER TABLE Profile ADD CONSTRAINT PK_PROFILE PRIMARY KEY (
	M_ID,
	R_N,
	B_N,
	M_ID2
);

ALTER TABLE Board_Recruit ADD CONSTRAINT PK_BOARD_RECRUIT PRIMARY KEY (
	B_N,
	M_ID,
	CA_N
);

ALTER TABLE Comment ADD CONSTRAINT PK_COMMENT PRIMARY KEY (
	C_N,
	BM_N,
	M_ID,
	Image_N
);

ALTER TABLE Chating ADD CONSTRAINT PK_CHATING PRIMARY KEY (
	B_N,
	M_ID
);

ALTER TABLE TIME ADD CONSTRAINT PK_TIME PRIMARY KEY (
	B_N
);

ALTER TABLE Application ADD CONSTRAINT PK_APPLICATION PRIMARY KEY (
	AP_N,
	B_N,
	M_ID
);

ALTER TABLE Review ADD CONSTRAINT PK_REVIEW PRIMARY KEY (
	R_N,
	B_N,
	M_ID
);

ALTER TABLE Category ADD CONSTRAINT PK_CATEGORY PRIMARY KEY (
	CA_N
);

ALTER TABLE Board_Market ADD CONSTRAINT PK_BOARD_MARKET PRIMARY KEY (
	BM_N,
	M_ID,
	CA_N,
	Image_N
);

ALTER TABLE Image ADD CONSTRAINT PK_IMAGE PRIMARY KEY (
	Image_N
);

ALTER TABLE Board_Notice ADD CONSTRAINT PK_BOARD_NOTICE PRIMARY KEY (
	BN_N,
	M_ID
);

ALTER TABLE Wish ADD CONSTRAINT PK_WISH PRIMARY KEY (
	W_N,
	B_N,
	M_ID,
	CA_N
);

ALTER TABLE Board_Question ADD CONSTRAINT PK_BOARD_QUESTION PRIMARY KEY (
	BQ_N,
	M_ID
);

ALTER TABLE Report ADD CONSTRAINT PK_REPORT PRIMARY KEY (
	R_N,
	M_ID
);

ALTER TABLE Profile ADD CONSTRAINT FK_Member_TO_Profile_1 FOREIGN KEY (
	M_ID
)
REFERENCES Member (
	M_ID
);

ALTER TABLE Profile ADD CONSTRAINT FK_Review_TO_Profile_1 FOREIGN KEY (
	R_N
)
REFERENCES Review (
	R_N
);

ALTER TABLE Profile ADD CONSTRAINT FK_Review_TO_Profile_2 FOREIGN KEY (
	B_N
)
REFERENCES Review (
	B_N
);

ALTER TABLE Profile ADD CONSTRAINT FK_Review_TO_Profile_3 FOREIGN KEY (
	M_ID2
)
REFERENCES Review (
	M_ID
);

ALTER TABLE Board_Recruit ADD CONSTRAINT FK_Member_TO_Board_Recruit_1 FOREIGN KEY (
	M_ID
)
REFERENCES Member (
	M_ID
);

ALTER TABLE Board_Recruit ADD CONSTRAINT FK_Category_TO_Board_Recruit_1 FOREIGN KEY (
	CA_N
)
REFERENCES Category (
	CA_N
);

ALTER TABLE Comment ADD CONSTRAINT FK_Board_Market_TO_Comment_1 FOREIGN KEY (
	BM_N
)
REFERENCES Board_Market (
	BM_N
);

ALTER TABLE Comment ADD CONSTRAINT FK_Board_Market_TO_Comment_2 FOREIGN KEY (
	M_ID
)
REFERENCES Board_Market (
	M_ID
);

ALTER TABLE Comment ADD CONSTRAINT FK_Board_Market_TO_Comment_3 FOREIGN KEY (
	Image_N
)
REFERENCES Board_Market (
	Image_N
);

ALTER TABLE Chating ADD CONSTRAINT FK_Board_Recruit_TO_Chating_1 FOREIGN KEY (
	B_N
)
REFERENCES Board_Recruit (
	B_N
);

ALTER TABLE Chating ADD CONSTRAINT FK_Board_Recruit_TO_Chating_2 FOREIGN KEY (
	M_ID
)
REFERENCES Board_Recruit (
	M_ID
);

ALTER TABLE TIME ADD CONSTRAINT FK_Board_Recruit_TO_TIME_1 FOREIGN KEY (
	B_N
)
REFERENCES Board_Recruit (
	B_N
);

ALTER TABLE Application ADD CONSTRAINT FK_Board_Recruit_TO_Application_1 FOREIGN KEY (
	B_N
)
REFERENCES Board_Recruit (
	B_N
);

ALTER TABLE Application ADD CONSTRAINT FK_Board_Recruit_TO_Application_2 FOREIGN KEY (
	M_ID
)
REFERENCES Board_Recruit (
	M_ID
);

ALTER TABLE Review ADD CONSTRAINT FK_Board_Recruit_TO_Review_1 FOREIGN KEY (
	B_N
)
REFERENCES Board_Recruit (
	B_N
);

ALTER TABLE Review ADD CONSTRAINT FK_Board_Recruit_TO_Review_2 FOREIGN KEY (
	M_ID
)
REFERENCES Board_Recruit (
	M_ID
);

ALTER TABLE Board_Market ADD CONSTRAINT FK_Member_TO_Board_Market_1 FOREIGN KEY (
	M_ID
)
REFERENCES Member (
	M_ID
);

ALTER TABLE Board_Market ADD CONSTRAINT FK_Category_TO_Board_Market_1 FOREIGN KEY (
	CA_N
)
REFERENCES Category (
	CA_N
);

ALTER TABLE Board_Market ADD CONSTRAINT FK_Image_TO_Board_Market_1 FOREIGN KEY (
	Image_N
)
REFERENCES Image (
	Image_N
);

ALTER TABLE Board_Notice ADD CONSTRAINT FK_Member_TO_Board_Notice_1 FOREIGN KEY (
	M_ID
)
REFERENCES Member (
	M_ID
);

ALTER TABLE Wish ADD CONSTRAINT FK_Board_Recruit_TO_Wish_1 FOREIGN KEY (
	B_N
)
REFERENCES Board_Recruit (
	B_N
);

ALTER TABLE Wish ADD CONSTRAINT FK_Board_Recruit_TO_Wish_2 FOREIGN KEY (
	M_ID
)
REFERENCES Board_Recruit (
	M_ID
);

ALTER TABLE Wish ADD CONSTRAINT FK_Board_Recruit_TO_Wish_3 FOREIGN KEY (
	CA_N
)
REFERENCES Board_Recruit (
	CA_N
);

ALTER TABLE Board_Question ADD CONSTRAINT FK_Member_TO_Board_Question_1 FOREIGN KEY (
	M_ID
)
REFERENCES Member (
	M_ID
);

ALTER TABLE Report ADD CONSTRAINT FK_Member_TO_Report_1 FOREIGN KEY (
	M_ID
)
REFERENCES Member (
	M_ID
);

